### ISSUE TITLE
constants should be placed outside of your function

### ISSUE THREAD

**Issue by incredibleLeitman** [B-ANTONY-J/High_Low_Number-Guessing_Game#1]
https://github.com/B-ANTONY-J/High_Low_Number-Guessing_Game/blob/a58fbd7aaea3f3ced9067c91be88db436b646a95/High_Low_Number%20Guessing_Game/Program.cs#L12-L13

You already had this before but in a recent commit moved them back there, why?

**Comment by incredibleLeitman** [comment]
Also "MAGIC_NUM" is a very bad variable name that could mean anything 🙈 
This variable was already named WITHIN_FIVE why did you reverted it?

**Comment by B-ANTONY-J** [comment]
Constant variables move outside of function
