### ISSUE TITLE
Math.Abs not needed for always positive numbers

### ISSUE THREAD

**Issue by incredibleLeitman** [B-ANTONY-J/High_Low_Number-Guessing_Game#2]
https://github.com/B-ANTONY-J/High_Low_Number-Guessing_Game/blob/a58fbd7aaea3f3ced9067c91be88db436b646a95/High_Low_Number%20Guessing_Game/Program.cs#L14-L15

I have mentioned this already in feedback twice, why don't you remove that?

In your code, MAGIC_NUM is equal to 5 and should always be a positive number, otherwise your program would not work.
When multiplying a positive number by another positive number, there is NO way that this results in a negative number (when within the boundaries of the datatype) so you don't need to call Math.Abs to convert this to a positive number
```int equalsTwenty = 4 * MAGIC_NUM;``` would return the same value as with using Math.Abs

**Comment by B-ANTONY-J** [comment]
Math.Abs has been removed from the code structure
